import type { FC } from 'hono/jsx'

/**
 * Generic page component which renders an arbitrary HTML string.  The
 * `dangerouslySetInnerHTML` prop is used to insert pre‑sanitised content.  You
 * should ensure that the HTML is generated by trusted code (see
 * `utils/editor.ts` for details).
 */
const Page: FC<{ html: string }> = ({ html }) => {
  return (
    <div
      class="prose prose-slate max-w-none"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}

export default Page